# README: 
# Disaster recovery in the case that the entire google account with firestore data gets wiped somehow 
# Sync daily backups from storage buckets to github artifacts which should persist for 90 days 

# Decyption (you will be prompted for pin-entry)
# Symetrical 256 bit ancryption with passphrase in repository secrets 
# All collaboraters (write access) will be able to manually extract the repo secret with a custom script if needed
# gpg --decrypt encrypted > decrypted

name: Firestore Backup

on:
  workflow_dispatch: # allow action to be run manually 
  schedule:
    - cron:  '0 0 * * *' # everyday at midnight
  pull_request: # temporary
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: google-github-actions/setup-gcloud@master
      name: Set up Google Cloud SDK
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      env:
        BACKUP_SECRET: ${{ secrets.BACKUP_SECRET }}
      run: |
        # Save version info of gpg tool in case implementations change in later versions
        mkdir artifacts
        gpg --version > ./artifacts/GPG_VERSION 
        # Clone backup folder
        gsutil cp gs://backups.ehs-service.org/test/clocktree.cpp ./artifacts/clocktree.cpp # test file
        # Encrypt backup with symetric key
        gpg --pinentry-mode loopback --passphrase "${BACKUP_SECRET}" --output ./artifacts/encrypted --symmetric --cipher-algo AES256 ./artifacts/clocktree.cpp

    - name: Archive databse to actions artifacts
      uses: actions/upload-artifact@v2
      with:
          name: backup-latest
          path: ./artifacts # test file
