name: Firestore Backup

on:
  workflow_dispatch: # allow action to be run manually 
  schedule:
    - cron:  '0 0 * * *' # everyday at midnight
  pull_request: # temporary
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: google-github-actions/setup-gcloud@master
      name: Set up Google Cloud SDK
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: |
        gsutil cp gs://backups.ehs-service.org/test/clocktree.cpp ./clocktree.cpp # test file
        gpg --passphrase "test" --output ./encrypted --symmetric --cipher-algo AES256 ./clocktree.cpp

        
    - name: Archive databse to actions artifacts
      uses: actions/upload-artifact@v2
      with:
          name: backup-latest
          path: ./encrypted # test file
