name: Update License


on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo
      - uses: actions/checkout@v2
      
      # Creat New Branch
      - name: Create New Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'license'
          
      # Switch to New Branch
      - uses: actions/checkout@v2
        with:
          ref: my-branch

      # This uses sed to change the year
      - name: Edit The License File
        run: |
          cd ./actions/license
          python update.py
      
      # Committing The Changes
      - name: Commit Changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions Bot"
          git add .
          git commit -m 'Update license year' || true # pass is there is nothing to commit
          git push
      
      # Create PR
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "license"
          destination_branch: "master"
          pr_title: "Update License"
          pr_body: "*An automated License Update PR*"
          pr_label: "actions"
          github_token: ${{ secrets.GITHUB_TOKEN }}
