name: Update License


on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo
      - uses: actions/checkout@v2

      # This uses sed to change the year
      - name: Edit the license file
        run: |
          cd ./actions/license
          python update.py
      
      # Create PR
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "license"
          destination_branch: "master"
          pr_title: "Update License"
          pr_body: ":crown: *An automated PR*"
          pr_label: "action"
          github_token: ${{ secrets.GITHUB_TOKEN }}
