name: CI

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate Website Screenshots
      run: |
         pip3 install --upgrade pip
         export BROWSERSTACK_KEY=${{secrets.BROWSERSTACK_KEY}}
         pip3 install selenium
         cd Actions/screenshots && python3 screenshot.py
         
    - uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: Actions/screenshots/*.png
