name: Tests

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'
  push:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache website modules
      with:
        path: |
          ./website/node_modules
        key: ${{ runner.os }}-website-modules-${{ hashFiles('./website/yarn.lock') }}

    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn 
         yarn test

    - name: Cache firebase emulators
      uses: actions/cache@v2
      with:
        path: ${{ env.FIREBASE_EMULATORS_PATH }}
        key:
          ${{ runner.os }}-firebase-emulators-${{
          hashFiles('./Firebase/Tests/yarn.lock') }}


    - uses: actions/cache@v2
      name: Cache database modules
      with:
        path: |
          ./Firebase/Tests/node_modules
        key: ${{ runner.os }}-database-modules-${{ hashFiles('./Firebase/Tests/yarn.lock') }}


    - name: Run Database Unit Test
      run: |
         cd Firebase/Tests 
         yarn 
         yarn ci
