name: Tests

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache website modules
      with:
        path: |
          ./website/node_modules
        key: ${{ runner.os }}-website-modules-${{ hashFiles('./website/yarn.lock') }}

    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn 
         yarn test

    - uses: actions/cache@v2
      name: Cache database modules and firebase binary
      with:
        path: |
          ./Firebase/Tests/node_modules
          ${{ github.workspace }}/emulator-cache
        key: ${{ runner.os }}-database-${{ hashFiles('./Firebase/Tests/yarn.lock') }}


    - name: Run Database Unit Test
      run: |
         cd Firebase/Tests 
         yarn 
         yarn ci
