name: CI:Tests

# Run on any commit or pr on any branch
on:
  pull_request:
    branches:
      - '**'
  push:
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache yarn and node modules
      with:
        path: |
          $GITHUB_WORKSPACE/website/node_modules
          ./Firebase/Tests/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/+(yarn.lock|package-lock.json)') }}

    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn 
         yarn test

    - name: Cache firebase emulators
      uses: actions/cache@v2
      with:
        path: ${{ env.FIREBASE_EMULATORS_PATH }}
        key:
          ${{ runner.os }}-firebase-emulators-${{
          hashFiles('emulator-cache/**') }}


    - name: Run Database Unit Test
      run: |
         cd Firebase/Tests 
         yarn 
         yarn ci
