name: Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out the repository
    - uses: actions/checkout@v2
      name: Checkout repository

    # Caches the firebase emulator
    - uses: actions/cache@v2
      name: Cache firebase emulator
      with:
        path: /home/runner/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulator-${{ hashFiles('./Firebase/Tests/yarn.lock') }}

      # Caches the node_modules
    - uses: actions/cache@v2
      name: Cache node_modules
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        
    - name: Install node_modules if cache did not hit
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        (cd Firebase/Tests && yarn)
        (cd website && yarn)

    # Runs the website tests
    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn test

    # Runs the database tests
    - name: Run Database Unit Tests
      run: |
         cd Firebase/Tests 
         yarn ci

    # Check build output for errors
    - name: Check build for errors
      run: |
         cd website 
         yarn build
