name: Tests
#This comment is to test the cache. To test the cache, increment this number than commit the change: 1
# Run on any pr on any branch
on:
  pull_request:
    branches:
      - '**'


jobs:
  # This workflow contains a single job to run the tests
  build:
    runs-on: ubuntu-latest


    steps:
    # Checks-out the repository
    - uses: actions/checkout@v2

      #Caches the firebase emulator
    - uses: actions/cache@v2
      name: Cache database modules
      with:
        path: /home/runner/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulator-${{ hashFiles('./Firebase/Tests/yarn.lock') }}

      #Caches the node_modules
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    #Runs the website tests
    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn 
         yarn test

    - name: Install node modules if cache didn't hit
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        cd Firebase/Tests
        yarn
        yarn install
      
    #Runs the database tests
    - name: Run Database Unit Test
      run: |
         cd Firebase/Tests 
         yarn ci
