name: Tests

# Run on any pr on any branch
on:
  pull_request:
    branches:
      - '**'


jobs:
  # This workflow contains a single job to run the tests
  build:
    runs-on: ubuntu-latest


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #Caches the node_modules for the website tests
    - uses: actions/cache@v2
      name: Cache website modules
      with:
        path: |
          ./website/node_modules
        key: ${{ runner.os }}-website-modules-${{ hashFiles('./website/yarn.lock') }}

    #Runs the website tests
    - name: Run Website Unit Tests
      run: |
         cd website 
         yarn 
         yarn test

    #Caches the firebase emulator
    - uses: actions/cache@v2
      name: Cache database modules
      with:
        path: /home/runner/.cache/firebase/emulators
        key: ${{ runner.os }}-database-modules-${{ hashFiles('./Firebase/Tests/yarn.lock') }}

    #Caches the node_modules folder
    - uses: actions/cache@v2
      name: Cache firebase binary
      with:
        path: ./Firebase/Tests/node_modules
        key: ${{ runner.os }}-database-binary-${{ hashFiles('./Firebase/Tests/yarn.lock') }}

    #Runs the database tests
    - name: Run Database Unit Test
      run: |
         cd Firebase/Tests 
         yarn 
         yarn ci
